services:
  - type: web
    name: qdrant
    env: docker
    region: frankfurt # optional (defaults to oregon)
    plan: free
    branch: main # optional (defaults to master)
    numInstances: 1
    healthCheckPath: /healthz
    dockerfilePath: ./Dockerfile
    buildCommand: ""  # Qdrant n'a pas besoin de build command spécifique
    startCommand: ""  # Par défaut, le CMD du Dockerfile sera utilisé
    envVars:
      - key: QDRANT__DATABASE__URL
        value: postgres://<SUPABASE_USER>:<SUPABASE_PASSWORD>@<SUPABASE_HOST>:<SUPABASE_PORT>/<SUPABASE_DB>
      - key: QDRANT__API__KEY
        value: your-secure-api-key-here
      - key: PORT
        value: 6333
